# site settings
title: Karina T. Suero LMFT
subtitle: Therapy for Everyone
email: felipe@felipesuero.com
description: "Ready to get started?"
baseurl: "" # the subpath of your site, e.g. /blog
url:  https://karina-website.github.io # the base hostname & protocol for your site
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed