# site settings
title: Karina T. Suero LMFT
subtitle: Therapy for Everyone
email: karinasuero8@protonmail.com
description: "Ready to get started?"
baseurl: "/" # the subpath of your site, e.g. /blog
url:  www.karina-therapy.com # the base hostname & protocol for your site
street_address: 36 E Front Street 
city: Media
state: PA
zip_code: 19063
country: United States of America
phone: (484) 639 9475

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed